perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERVK 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERVL 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERVL-MaLR 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Baboon LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Baboon LTR ERVK 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Baboon LTR ERVL-MaLR 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Budgerigar LTR ERVL 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Bushbaby LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Chimp LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Chimp LTR ERVK 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Chimp LTR ERVL-MaLR 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Cow LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Cow LTR LTR 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Dog LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Ferret LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gibbon LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gibbon LTR ERVK 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gibbon LTR ERVL-MaLR 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gorilla LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gorilla LTR ERVK 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gorilla LTR ERVL-MaLR 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl GuineaPig LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl GuineaPig LTR MaLR 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Horse LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Human LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Human LTR ERVK 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Human LTR ERVL-MaLR 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Manatee LTR ERVL-MaLR 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Marmoset LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl MGfinch LTR ERVK 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl MGfinch LTR ERVL 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Microbat LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Microbat LTR ERVK 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl MLemur LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Mouse LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Mouse LTR ERVK 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Mouse LTR MaLR 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl NMrat LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Opossum LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Opossum LTR ERVK 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Orangutan LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Orangutan LTR ERVK 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Orangutan LTR MaLR 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Platypus LTR LTR 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rabbit LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rabbit LTR ERVK 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rat LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rat LTR ERVK 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rat LTR MaLR 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rhesus LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rhesus LTR ERVK 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rhesus LTR MaLR 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl RockHyrax LTR ERVL-MaLR 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Sloth LTR ERVL 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl SMonkey LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Squirrel LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Squirrel LTR ERVK 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Tarsier LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Tarsier LTR ERVK 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Tenrec LTR ERVL 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Wallaby LTR ERVK 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl WhiteRhino LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Zebrafinch LTR ERV1 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Zebrafinch LTR ERVK 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Zebrafinch LTR ERVL 0 5 GA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERVK 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERVL 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERVL-MaLR 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Baboon LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Baboon LTR ERVK 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Baboon LTR ERVL-MaLR 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Budgerigar LTR ERVL 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Bushbaby LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Chimp LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Chimp LTR ERVK 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Chimp LTR ERVL-MaLR 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Cow LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Cow LTR LTR 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Dog LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Ferret LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gibbon LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gibbon LTR ERVK 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gibbon LTR ERVL-MaLR 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gorilla LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gorilla LTR ERVK 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gorilla LTR ERVL-MaLR 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl GuineaPig LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl GuineaPig LTR MaLR 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Horse LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Human LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Human LTR ERVK 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Human LTR ERVL-MaLR 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Manatee LTR ERVL-MaLR 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Marmoset LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl MGfinch LTR ERVK 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl MGfinch LTR ERVL 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Microbat LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Microbat LTR ERVK 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl MLemur LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Mouse LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Mouse LTR ERVK 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Mouse LTR MaLR 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl NMrat LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Opossum LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Opossum LTR ERVK 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Orangutan LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Orangutan LTR ERVK 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Orangutan LTR MaLR 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Platypus LTR LTR 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rabbit LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rabbit LTR ERVK 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rat LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rat LTR ERVK 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rat LTR MaLR 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rhesus LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rhesus LTR ERVK 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rhesus LTR MaLR 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl RockHyrax LTR ERVL-MaLR 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Sloth LTR ERVL 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl SMonkey LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Squirrel LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Squirrel LTR ERVK 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Tarsier LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Tarsier LTR ERVK 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Tenrec LTR ERVL 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Wallaby LTR ERVK 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl WhiteRhino LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Zebrafinch LTR ERV1 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Zebrafinch LTR ERVK 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Zebrafinch LTR ERVL 0 5 CT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERVK 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERVL 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERVL-MaLR 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Baboon LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Baboon LTR ERVK 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Baboon LTR ERVL-MaLR 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Budgerigar LTR ERVL 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Bushbaby LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Chimp LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Chimp LTR ERVK 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Chimp LTR ERVL-MaLR 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Cow LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Cow LTR LTR 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Dog LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Ferret LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gibbon LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gibbon LTR ERVK 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gibbon LTR ERVL-MaLR 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gorilla LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gorilla LTR ERVK 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gorilla LTR ERVL-MaLR 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl GuineaPig LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl GuineaPig LTR MaLR 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Horse LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Human LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Human LTR ERVK 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Human LTR ERVL-MaLR 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Manatee LTR ERVL-MaLR 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Marmoset LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl MGfinch LTR ERVK 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl MGfinch LTR ERVL 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Microbat LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Microbat LTR ERVK 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl MLemur LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Mouse LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Mouse LTR ERVK 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Mouse LTR MaLR 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl NMrat LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Opossum LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Opossum LTR ERVK 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Orangutan LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Orangutan LTR ERVK 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Orangutan LTR MaLR 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Platypus LTR LTR 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rabbit LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rabbit LTR ERVK 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rat LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rat LTR ERVK 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rat LTR MaLR 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rhesus LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rhesus LTR ERVK 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rhesus LTR MaLR 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl RockHyrax LTR ERVL-MaLR 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Sloth LTR ERVL 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl SMonkey LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Squirrel LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Squirrel LTR ERVK 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Tarsier LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Tarsier LTR ERVK 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Tenrec LTR ERVL 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Wallaby LTR ERVK 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl WhiteRhino LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Zebrafinch LTR ERV1 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Zebrafinch LTR ERVK 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Zebrafinch LTR ERVL 0 5 GC
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERVK 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERVL 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERVL-MaLR 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Baboon LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Baboon LTR ERVK 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Baboon LTR ERVL-MaLR 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Budgerigar LTR ERVL 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Bushbaby LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Chimp LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Chimp LTR ERVK 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Chimp LTR ERVL-MaLR 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Cow LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Cow LTR LTR 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Dog LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Ferret LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gibbon LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gibbon LTR ERVK 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gibbon LTR ERVL-MaLR 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gorilla LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gorilla LTR ERVK 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gorilla LTR ERVL-MaLR 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl GuineaPig LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl GuineaPig LTR MaLR 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Horse LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Human LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Human LTR ERVK 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Human LTR ERVL-MaLR 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Manatee LTR ERVL-MaLR 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Marmoset LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl MGfinch LTR ERVK 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl MGfinch LTR ERVL 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Microbat LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Microbat LTR ERVK 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl MLemur LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Mouse LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Mouse LTR ERVK 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Mouse LTR MaLR 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl NMrat LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Opossum LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Opossum LTR ERVK 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Orangutan LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Orangutan LTR ERVK 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Orangutan LTR MaLR 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Platypus LTR LTR 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rabbit LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rabbit LTR ERVK 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rat LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rat LTR ERVK 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rat LTR MaLR 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rhesus LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rhesus LTR ERVK 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rhesus LTR MaLR 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl RockHyrax LTR ERVL-MaLR 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Sloth LTR ERVL 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl SMonkey LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Squirrel LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Squirrel LTR ERVK 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Tarsier LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Tarsier LTR ERVK 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Tenrec LTR ERVL 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Wallaby LTR ERVK 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl WhiteRhino LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Zebrafinch LTR ERV1 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Zebrafinch LTR ERVK 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Zebrafinch LTR ERVL 0 5 GT
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERVK 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERVL 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERVL-MaLR 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Baboon LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Baboon LTR ERVK 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Baboon LTR ERVL-MaLR 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Budgerigar LTR ERVL 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Bushbaby LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Chimp LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Chimp LTR ERVK 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Chimp LTR ERVL-MaLR 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Cow LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Cow LTR LTR 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Dog LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Ferret LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gibbon LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gibbon LTR ERVK 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gibbon LTR ERVL-MaLR 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gorilla LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gorilla LTR ERVK 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gorilla LTR ERVL-MaLR 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl GuineaPig LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl GuineaPig LTR MaLR 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Horse LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Human LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Human LTR ERVK 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Human LTR ERVL-MaLR 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Manatee LTR ERVL-MaLR 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Marmoset LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl MGfinch LTR ERVK 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl MGfinch LTR ERVL 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Microbat LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Microbat LTR ERVK 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl MLemur LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Mouse LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Mouse LTR ERVK 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Mouse LTR MaLR 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl NMrat LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Opossum LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Opossum LTR ERVK 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Orangutan LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Orangutan LTR ERVK 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Orangutan LTR MaLR 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Platypus LTR LTR 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rabbit LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rabbit LTR ERVK 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rat LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rat LTR ERVK 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rat LTR MaLR 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rhesus LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rhesus LTR ERVK 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rhesus LTR MaLR 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl RockHyrax LTR ERVL-MaLR 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Sloth LTR ERVL 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl SMonkey LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Squirrel LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Squirrel LTR ERVK 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Tarsier LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Tarsier LTR ERVK 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Tenrec LTR ERVL 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Wallaby LTR ERVK 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl WhiteRhino LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Zebrafinch LTR ERV1 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Zebrafinch LTR ERVK 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Zebrafinch LTR ERVL 0 5 CA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERVK 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERVL 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Armadillo LTR ERVL-MaLR 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Baboon LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Baboon LTR ERVK 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Baboon LTR ERVL-MaLR 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Budgerigar LTR ERVL 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Bushbaby LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Chimp LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Chimp LTR ERVK 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Chimp LTR ERVL-MaLR 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Cow LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Cow LTR LTR 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Dog LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Ferret LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gibbon LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gibbon LTR ERVK 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gibbon LTR ERVL-MaLR 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gorilla LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gorilla LTR ERVK 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Gorilla LTR ERVL-MaLR 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl GuineaPig LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl GuineaPig LTR MaLR 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Horse LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Human LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Human LTR ERVK 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Human LTR ERVL-MaLR 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Manatee LTR ERVL-MaLR 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Marmoset LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl MGfinch LTR ERVK 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl MGfinch LTR ERVL 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Microbat LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Microbat LTR ERVK 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl MLemur LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Mouse LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Mouse LTR ERVK 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Mouse LTR MaLR 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl NMrat LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Opossum LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Opossum LTR ERVK 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Orangutan LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Orangutan LTR ERVK 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Orangutan LTR MaLR 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Platypus LTR LTR 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rabbit LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rabbit LTR ERVK 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rat LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rat LTR ERVK 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rat LTR MaLR 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rhesus LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rhesus LTR ERVK 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Rhesus LTR MaLR 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl RockHyrax LTR ERVL-MaLR 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Sloth LTR ERVL 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl SMonkey LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Squirrel LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Squirrel LTR ERVK 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Tarsier LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Tarsier LTR ERVK 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Tenrec LTR ERVL 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Wallaby LTR ERVK 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl WhiteRhino LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Zebrafinch LTR ERV1 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Zebrafinch LTR ERVK 0 5 TA
perl516 /home/alu/binknis/Perl_DNAE/analysis_scripts/createTrackFiles2.pl Zebrafinch LTR ERVL 0 5 TA
